blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Posts
    path('posts/', views.posts, name='posts'),
    # Page for adding new post
    path('new_post/', views.new_post, name='new_post'),
    # Page for a single post
    path('posts/<int:post_id>/', views.post, name='post'),
    # Page for editing post
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    #Page for deleting post
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    

    # Page for commenting post
    path('comment_post/<int:post_id>/', views.comment_post, name='comment_post'),
    # Page for deleting comment
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    # Page for editing comment
    path('edit_comment/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    
    # Page for user's posts
    path('user_posts/', views.user_posts, name='user_posts'),
    # Page for adding new user's post
    #path('user_new_post/', views.user_new_post, name='user_new_post'),
]

users/urls.py
'''Defines URL patterns for users.'''

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
    '''Single post on the blog.'''
    #slug = models.SlugField(max_length=200 , unique=True)
    title = models.CharField(max_length=200)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    delete_flag = models.BooleanField(default=False)

    def __str__(self):
        '''Return a string representation of the model.'''
        return f'{self.title} {self.owner} {self.text}'

class Comment(models.Model):
    '''Comment section for posts.'''
    post = models.ForeignKey(BlogPost, related_name="comments", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering= ['-date_added']

    def __str__(self):
        return f"{self.title} {self.owner} {self.text}"

blogs/forms.py
from django import forms
from .models import BlogPost, Comment

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ('title', 'text', 'image')
        #labels = {'text': ''}    

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('title', 'text',)
        labels = {'text': ''}

class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text' : ''}

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost, Comment
from .forms import BlogPostForm, CommentForm


# Posts

def index(request):
    '''Home page'''
    return render(request, 'blogs/index.html')

def posts(request):
    '''Show all admin posts'''
    admin_posts = BlogPost.objects.filter(owner=1).filter(delete_flag=False).order_by('-date_added')
    context = {'posts': admin_posts}
    return render(request, 'blogs/posts.html', context)

def post(request, post_id):
    post = get_object_or_404(BlogPost, id=post_id)
    #post = BlogPost.objects.get(id=post_id)
    context = {'post' : post}
    return render(request, 'blogs/post.html', context)

@login_required
def new_post(request):
    '''Add a new post'''
    if request.method != 'POST':
        # create blank form
        form = BlogPostForm()
    else:
        # post data submitted; process data
        form = BlogPostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()

            if request.user.is_superuser:
                return redirect('blogs:posts')
            else:
                return redirect('blogs:user_posts')
    # Display blank form
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
    post = get_object_or_404(BlogPost, id=post_id)
    #post = BlogPost.objects.get(id=post_id)
    if post.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = BlogPostForm(instance=post)
    else:
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:post', post_id=post.id)
    context = {'post':post, 'form':form}
    return render(request, 'blogs/edit_post.html', context)

@login_required
def delete_post(request, post_id):
    post_to_delete = get_object_or_404(BlogPost, id=post_id)
    #post_to_delete = BlogPost.objects.get(id=post_id)
    if post_to_delete.owner != request.user:
        raise Http404
    else:
        if request.method == 'POST':
            post_to_delete.delete_flag = True
            post_to_delete.save()

            if request.user.is_superuser:
                return redirect('blogs:posts')
            else:
                return redirect('blogs:user_posts')
    context = {'post':post_to_delete}
    return render(request, 'blogs/delete_post.html', context)

# Comments

@login_required
def comment_post(request, post_id):
    post = get_object_or_404(BlogPost, id=post_id)
    #post = BlogPost.objects.get(id=post_id)
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.owner = request.user
            comment.save()
            return redirect('blogs:post', post_id=post_id)
    context = {'post':post, 'form': form}
    return render(request, 'blogs/comment_post.html', context)

@login_required
def edit_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    #comment = Comment.objects.get(id=comment_id)
    post = comment.post
    if comment.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = CommentForm(instance=comment)
    else:
        form = CommentForm(instance=comment, data=request.POST)
        if form.is_valid():
            comment.owner = request.user
            form.save()
            return redirect('blogs:post', post_id=post.id)
    context = {'comment':comment, 'post':post, 'form':form}
    return render(request, 'blogs/edit_comment.html', context)

@login_required
def delete_comment(request, comment_id):
    comment_to_delete = get_object_or_404(Comment, id=comment_id)
    #comment_to_delete = Comment.objects.get(id=comment_id)
    post = comment_to_delete.post
    if comment_to_delete.owner != request.user:
        raise Http404
    else:
        if request.method == 'POST':
            comment_to_delete.delete()
            return redirect('blogs:post', post_id=post.id)
    context = {'comment':comment_to_delete, 'post':post}
    return render(request, 'blogs/delete_comment.html', context)


# User

@login_required
def user_posts(request):
    user_posts = BlogPost.objects.filter(delete_flag=False).exclude(owner=1).order_by('-date_added')
    context = {'user_posts': user_posts}
    return render(request, 'blogs/user_posts.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
    <title>My awesome blog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">
        <a class="navbar-brand" href="{% url 'blogs:index' %}">
            My awesome blog</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:posts' %}">
                        Posts</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:user_posts' %}">
                        User posts</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text"}">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>

</html>

blogs/templates/blogs/comment_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h3> Comment post: <br> {{post.title}}|{{post.owner}} </h3>
{% endblock page_header %}

{% block content %}

<form action="{% url 'blogs:comment_post' post.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-dark">Add comment</button>
    {% endbuttons %}
    
</form>
{% endblock content %}

blogs/templates/blogs/delete_comment.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h3> Delete: "{{comment.title}}"? </h3>
{% endblock page_header %}

{% block content %}
<form action="{% url 'blogs:delete_comment' comment.id %}" method="post">
    {% csrf_token %}

    {% buttons %}
    <button name="submit" class="btn btn-dark">Delete</button>
    {% endbuttons %}
</form>
{% endblock content %}

blogs/templates/blogs/delete_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h3> Delete: "{{post.title}}"? </h3>
{% endblock page_header %}

{% block content %}
<form action="{% url 'blogs:delete_post' post.id %}" method="post">
    {% csrf_token %}

    {% buttons %}
    <button name="submit" class="btn btn-dark">Delete</button>
    {% endbuttons %}
</form>
{% endblock content %}

blogs/templates/blogs/edit_comment.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h3> {{comment.title}} | {{comment.owner}} </h3>
{% endblock page_header %}

{% block content %}
<form action="{% url 'blogs:edit_comment' comment.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-dark">Save changes</button>
    {% endbuttons %}
</form>
{% endblock content %}

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h3> {{post.title}} </h3>
{% endblock page_header %}

{% block content %}
<form action="{% url 'blogs:edit_post' post.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-dark">Save changes</button>
    {% endbuttons %}
</form>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">My awesome blog.</h1>
        <hr>
        <h2>Join me on my journey to learn Django.</h2>
        <hr>
        <p class="lead">
            This blog is my little diary. I am writing down the progress 
            and problems encountered while writing the code.
            
            As a registered user, you can also create your own posts and 
            other users can comment on them.
        </p>
        <a class="btn btn-lg btn-dark" href="{% url 'blogs:posts' %}"
 role="button">See my progress &raquo;</a>
    </div>
{% endblock page_header %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h3> Add a new post </h3>
{% endblock page_header %}

{% block content %}

<form action="{% url 'blogs:new_post' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-dark">Add post</button>
    {% endbuttons %}
    
</form>
{% endblock content %}

blogs/templates/blogs/post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="card mb-3">
        <h3 class="card-header">
            {{post.title}} | {{post.owner}} | {{post.date_added|date:'d M Y' }}
        </h3>
        <div class="card-body">
            {{ post.text|linebreaks }}
            <br>
            {% if post.image %}
            <img src="{{post.image.url}}" class="img-fluid" alt="" style="vertical-align:baseline;max-height:720px">
            <br>
            {% endif %}
            <hr>
            <br>
            <a class="btn btn-lg btn-dark btn-sm" href="{% url 'blogs:edit_post' post.id %}"
                role="button">Edit</a> <a class="btn btn-sm btn-dark" href="{% url 'blogs:delete_post' post.id %}"
                role="button">Delete</a>
    </div>
</div>
<br>
<br>
    <h5 class="text-info">Comments...</h5>
    
        {% if not post.comments.all %} 
            No comments... <a href="{% url 'blogs:comment_post' post.id %}" class="text-secondary">Add one!</a>
            <br>
            <br>
        {% else %}
        <br>
        <a class="btn btn-lg btn-info btn-sm" href="{% url 'blogs:comment_post' post.id %}"
            role="button">Add comment</a>
        <br>
        <br>
        {% for comment in post.comments.all %}
            <hr>
            <h6 class="text-warning">{{ comment.title}} | {{comment.owner}} | {{comment.date_added}}</h6>
            <br>
            {{comment.text}}
            <br>
            <br>
            <a class="btn btn-lg btn-dark btn-sm" href="{% url 'blogs:edit_comment' comment.id %}"
                role="button">Edit</a>
                <a class="btn btn-lg btn-dark btn-sm" href="{% url 'blogs:delete_comment' comment.id %}"
                role="button">Delete</a>
            <hr>
            {% endfor %}

        {% endif %}

{% endblock content %}

blogs/templates/blogs/posts.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h1>Posts</h1>
{% endblock page_header %}

{% block content %}

<a class="btn btn-lg btn-dark" href="{% url 'blogs:new_post' %}"
 role="button">Add new post &raquo;</a>
 <br>
 <br>
<ul>
    {% for post in posts %}
    <div class="card mb-3">
        <h4 class="card-header">
            <a href="{% url 'blogs:post' post.id %}" class="text-success">{{post.title}} | {{post.owner}}</a>
        </h4>
        <div class="card-body">
            {{ post.text|linebreaks }}
        </div>
    </div>

    {% empty %}
        <li><h3>No posts added yet.</h3></li>
    {% endfor %}    
</ul>

{% endblock content %}

blogs/templates/blogs/user_posts.html
{% extends "blogs/base.html" %}
{% block page_header %}
<h1>User posts</h1>
{% endblock page_header %}

{% block content %}

<a class="btn btn-lg btn-dark" href="{% url 'blogs:new_post' %}"
 role="button">Add new post &raquo;</a>
 <br>
 <br>
<ul>
    {% for post in user_posts %}

    <div class="card mb-3">
        <h4 class="card-header">
            <a href="{% url 'blogs:post' post.id %}" class="text-success">{{post.title}} | {{post.owner}}</a>
        </h4>
        <div class="card-body">
            {{ post.text|linebreaks }}
        </div>
    </div>
        <hr>
    {% empty %}
        <li><h3>No posts added yet.</h3></li>
    {% endfor %}    
</ul>

{% endblock content %}